default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: "password"
  host: db
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: open_medical_development

test:
  <<: *default
  database: open_medical_test

production:
  <<: *default
  database: open_medical_production
  username: open_medical
  password: <%= ENV['OPEN_MEDICAL_DATABASE_PASSWORD'] %>
